### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by Rinma** [Affehund/Skiing#1]
Hi, I like this mod. I started to build a small ski resort and there would be some items that would help:
- Signs to mark slopes. Like a sign at the beginning of which difficulty it is and some to mark the slope itself (maybe a little black cube-like thingy)
- Snowboards (otherwise it is unplayable 😂)

Something I really don't need but would be super cool:
- Lifts to get back up again

**Comment by Affehund** [comment]
Great to hear that you like the mod!

Signs to mark the slopes are a very good idea. I am sure I will add them soon.
The mod itself is more a skiing mod, but I will maybe add snowboards in one of the next updates (as many would like to have snowboards, too).
About the lifts:
This will probably take a while to implement, and I am not sure if I’ll ever add them.

Thanks a lot for the suggestions!
