### ISSUE TITLE
Dog sleds!

### ISSUE THREAD

**Issue by Laktostolerant** [Affehund/Skiing#3]
Would it be possible to make sleds able to be connected to tamed dogs through leads?
I think it would make for a great way of transportation!
Example image
![sled](https://user-images.githubusercontent.com/56837283/147853659-3980743e-ca1b-4fec-b6c9-bddea5602e24.png)
;

**Comment by danielschuster-muc** [comment]
Hi, thank you for your suggestion.
Leashing/Connecting dogs to the sleds is definitely on my todo list for the skiing mod.

**Comment by Affehund** [comment]
Thank you for your idea!
Dogs sleds are planned and will be definitely added soon, but I can’t tell you how long it will take to implement this feature.

**Comment by Laktostolerant** [comment]
Ay looking forward to them then! And I think you may have switched the labels around on the two issues-
