### ISSUE TITLE
Snow-covered grass not counting as #skiing:snowy_blocks, and skis & snowboards sink into ground

### ISSUE THREAD

**Issue by Laktostolerant** [Affehund/Skiing#4]
As title said, skis currently sink through thin snow layers, meaning you have to break the snow layer to actually access the ski and ride it

Also, grass blocks with snow on top of them don't currently count as #skiing:snowy_blocks, only the snow layer on top, but since the ski sinks through said block it doesn't go faster. This results in skiing at snail speed :P

**Comment by Affehund** [comment]
Thank you for reporting those bugs. I will have a look at them and see what I can do to fix those.
