### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by zachsai** [Affehund/Skiing#6]
![image](https://user-images.githubusercontent.com/63996164/149061006-6954fd13-5d84-48ca-b290-cc22cbc44f08.png)
Image is self explanatory, this is for wood from Blue Skies mod

**Comment by Affehund** [comment]
Thank you for submitting this issue. I could reproduce this error and will see what I can do to fix it. Its probably just an issue with the models / registry of the skiing mod and should be fixable.
